-- Add migration script here
create table if not exists notification_group
(
    id          bigint generated by default as identity,
    name        varchar     not null default '' unique,
    admin_email varchar     not null default '',
    token       varchar     not null default '',
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz not null default current_timestamp
);

alter table notification_group
    add constraint notification_group_id_pk primary key (id);

create table if not exists notification_subscriber
(
    id         bigint generated by default as identity,
    user_id    bigint      not null default 0,
    group_id   bigint      not null references notification_group (id) on delete cascade,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

alter table notification_subscriber
    add constraint notification_subscriber_id_pk primary key (id);

create table if not exists notification_message
(
    id         bigint generated by default as identity,
    channel    varchar     not null default '',
    subject    varchar     not null default '',
    message    varchar     not null default '',
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

alter table notification_message
    add constraint notification_message_id_pk primary key (id);
